export interface QuestionDescription {
    item: string;
    passa: boolean;
}

export const questions: Array<QuestionDescription> = [
    {item: 'Água', passa: true},
    {item: 'Óculos', passa: true},
    {item: 'Palácio', passa: true},
    {item: 'Frango', passa: false},
    {item: 'Carro', passa: false},
    {item: 'Café', passa: true},
    {item: 'Gato', passa: false},
    {item: 'Camarão', passa: true},
    {item: 'Árvore', passa: true},
    {item: 'Maçã', passa: true},
    {item: 'Pão', passa: true},
    {item: 'Avião', passa: true},
    {item: 'Bola', passa: false},
    {item: 'Mesa', passa: false},
    {item: 'Cavalo', passa: false},
    {item: 'Pássaro', passa: true},
    {item: 'Álcool', passa: true},
    {item: 'Cápsula', passa: true},
    {item: 'Cérebro', passa: true},
    {item: 'Cômoda', passa: true},
    {item: 'Balão', passa: true},
    {item: 'Lâmpada', passa: true},
    {item: 'Lampião', passa: true},
    {item: 'Mamão', passa: true},
    {item: 'Garfo', passa: false},
    {item: 'Abacaxi', passa: false},
    {item: 'Bolacha', passa: false},
    {item: 'Cachorro', passa: false},
    {item: 'Dente', passa: false},
    {item: 'Farinha', passa: false},
    {item: 'Jornal', passa: false},
    {item: 'Laranja', passa: false},
    {item: 'Manteiga', passa: false},
    {item: 'Ovo', passa: false},
    {item: 'Ventilador', passa: false},
    {item: 'Barco', passa: false},
    {item: "Queijo", passa: false},
    {item: "Rato", passa: false},
    {item: "Sabão", passa: true},
    {item: "Tigela", passa: false},
    {item: "Uva", passa: false},
    {item: "Vaso", passa: false},
    {item: "Xícara", passa: true},
    {item: "Zebra", passa: false},
    {item: "Chapéu", passa: true},
    {item: "Bambolê", passa: true},
    {item: "Televisão", passa: true},
    {item: "Lápis", passa: true},
    {item: "Relógio", passa: true},
    {item: "Buquê", passa: true},
    {item: "Burgês", passa: true},
    {item: "Anão", passa: true},
    {item: "Computador", passa: false},
    {item: "Caneta", passa: false},
    {item: "Bote", passa: false},
    {item: "Celular", passa: false},
    {item: "Bicicleta", passa: false},
    {item: "Mochila", passa: false},
    {item: "Planador", passa: false}
];
  